name: Build and Deploy WordPress Plugin in dev environment

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: |
          pwd
          git config --global http.sslverify false
          git clone --branch "${{ github.event.inputs.GIT_BRANCH}}" "https://${{ github.repository_owner }}:${{ secrets.GH_PASSWORD }}@github.com/atex-ci/nikita.git" .
          ls -la
          
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup monorepo
        run: |
          cd nikita
          pnpm setup-monorepo

      - name: Create artifact
        run: |
          cp -r apps/wordpress/plugin .
          cd plugin
          rm -rf data tests .phpcs.xml.dist phpstan.neon phpunit.xml.dist
          cd ..
          zip -r plugin.zip plugin
          rm -r plugin

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: wordpress-plugin
          path: plugin.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download plugin artifact
        uses: actions/download-artifact@v4
        with:
          name: wordpress-plugin

      - name: Upload plugin to WordPress dev
        run: |
          curl -X POST \
            -u "${{ secrets.WP_USER }}:${{ secrets.WP_APP_PASSWORD }}" \
            -F "plugin=@wordpress-plugin.zip" \
            -F "slug=plugin" \
            -F "status=active" \
            "https://wordpress.dev.atexcloud.io/wp-json/wp/v2/plugins/plugin/mytype-for-wordpress"
