name: multi-deploy

on:
  workflow_dispatch:
    inputs:
      env_list:
        description: 'customer ids to deploy (comma-separated, no spaces)'
        required: true
        default: ''
      branch:
        description: 'Git branch'
        required: true
        default: 'main'
      git_hash:
        description: 'Git commit hash'
        required: true
        default: ''

jobs:
  deploy-sequentially:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Process deployments sequentially
        id: deploy-loop
        run: |
          # Get the list of environments
          ENV_LIST="${{ github.event.inputs.env_list }}"
          BRANCH="${{ github.event.inputs.branch }}"
          GIT_HASH="${{ github.event.inputs.git_hash }}"
          
          # Split into array
          IFS=',' read -ra ENVS <<< "$ENV_LIST"
          
          # Initialize arrays for completed and pending
          COMPLETED=()
          PENDING=("${ENVS[@]}")
          
          echo "Starting sequential deployments of ${#ENVS[@]} environments"
          echo "Full environment list: $ENV_LIST"
          
          # FIRST: Update gist with all environments as pending
          PENDING_STR=$(IFS=,; echo "${PENDING[*]}")
          COMPLETED_STR=""
          
          echo "Initial update - Setting all environments as pending"
          echo "Pending: $PENDING_STR"
          
          # Create payload file for initial update
          echo '{
            "ref": "'$BRANCH'",
            "inputs": {
              "completed_deploys": "'$COMPLETED_STR'",
              "pending_deploys": "'$PENDING_STR'",
              "branch": "'$BRANCH'",
              "git_hash": "'$GIT_HASH'"
            }
          }' > initial_payload.json

          cat initial_payload.json
          
          # Initial update of the gist
          curl -s -X POST \
            -H "Authorization: token $MY_GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/update-deploy-status.yml/dispatches" \
            -d @initial_payload.json
          
          # Wait briefly for the initial status update
          sleep 2
          
          # Process each environment sequentially
          for ENV in "${ENVS[@]}"; do
            echo "===== Processing environment: $ENV ====="
            
            # Call manual-build workflow
            echo "Calling manual-build for environment $ENV..."
            
            # Create payload for manual-build workflow
            MANUAL_BUILD_PAYLOAD="{\"ref\":\"main\",\"inputs\":{ \"GIT_BRANCH\": \"$BRANCH\", \"ENVIRONMENT\": \"$ENV\", \"SKIP_TESTS\": \"true\" }}"
            
            echo "manual-build payload: $MANUAL_BUILD_PAYLOAD"
            
            # Call the manual-build workflow and capture the response
            RESPONSE=$(curl -s -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $MY_GITHUB_TOKEN" \
              "https://api.github.com/repos/atex-ci/nikita-runner/actions/workflows/manual-build.yml/dispatches" \
              -d "$MANUAL_BUILD_PAYLOAD")
            
            echo "manual-build triggered for environment: $ENV"
            
            # Wait for the workflow to complete
            echo "Waiting for manual-build workflow to complete..."
            
            # Sleep a bit to make sure the workflow has been registered
            sleep 5
            
            # Check workflow status every 30 seconds until complete
            WORKFLOW_COMPLETE=false
            MAX_ATTEMPTS=120  # Maximum wait time: 60 minutes
            ATTEMPT=0
            
            while [ "$WORKFLOW_COMPLETE" = false ] && [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
              # Check if there are any manual-build workflows running
              RUNNING_RESPONSE=$(curl -s \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $MY_GITHUB_TOKEN" \
                "https://api.github.com/repos/atex-ci/nikita-runner/actions/runs?status=in_progress")
              
              QUEUED_RESPONSE=$(curl -s \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $MY_GITHUB_TOKEN" \
                "https://api.github.com/repos/atex-ci/nikita-runner/actions/runs?status=queued")
              
              # Count running manual-builds
              RUNNING_COUNT=$(echo "$RUNNING_RESPONSE" | grep -o '"manual-build.yml"' | wc -l)
              QUEUED_COUNT=$(echo "$QUEUED_RESPONSE" | grep -o '"manual-build.yml"' | wc -l)
              
              echo "Found $RUNNING_COUNT running and $QUEUED_COUNT queued manual-build workflows"
              
              # If no manual-builds are running or queued, consider it complete
              if [ $RUNNING_COUNT -eq 0 ] && [ $QUEUED_COUNT -eq 0 ]; then
                WORKFLOW_COMPLETE=true
                echo "No manual-build workflows running or queued. Considering build complete."
              else
                echo "Workflow still running. Waiting 30 seconds before checking again. Attempt $ATTEMPT of $MAX_ATTEMPTS"
                sleep 30
                ATTEMPT=$((ATTEMPT + 1))
              fi
            done
            
            if [ "$WORKFLOW_COMPLETE" = false ]; then
              echo "WARNING: Timed out waiting for workflow to complete! Moving on to next environment."
            else
              echo "Build for $ENV completed!"
            fi
            
            # Now update arrays AFTER the build is complete
            # Remove current env from pending and add to completed
            COMPLETED+=("$ENV")
            
            # Rebuild the pending list without the current env
            NEW_PENDING=()
            for PEND in "${PENDING[@]}"; do
              if [ "$PEND" != "$ENV" ]; then
                NEW_PENDING+=("$PEND")
              fi
            done
            PENDING=("${NEW_PENDING[@]}")
            
            # Convert arrays to comma-separated strings
            COMPLETED_STR=$(IFS=,; echo "${COMPLETED[*]}")
            PENDING_STR=$(IFS=,; echo "${PENDING[*]}")
            
            echo "Completed: $COMPLETED_STR"
            echo "Pending: $PENDING_STR"
            
            # Update the gist AFTER the build is complete
            echo "Updating deployment status in gist after build..."
            echo '{
              "ref": "'$BRANCH'",
              "inputs": {
                "completed_deploys": "'$COMPLETED_STR'",
                "pending_deploys": "'$PENDING_STR'",
                "branch": "'$BRANCH'",
                "git_hash": "'$GIT_HASH'"
              }
            }' > payload.json

            cat payload.json
            
            # Update the gist by calling the update-deploy-status workflow
            curl -s -X POST \
              -H "Authorization: token $MY_GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/update-deploy-status.yml/dispatches" \
              -d @payload.json
            
            # Wait briefly for the status update workflow to start
            sleep 2
            
            echo "Status update triggered for environment: $ENV"
          done
          
          
          echo "All deployments have been completed and status has been finalized!"
        env:
          MY_GITHUB_TOKEN: ${{ secrets.GH_PASSWORD }}